from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .schemas import PredictionResult

try:
    import torch
except Exception:  # pragma: no cover - optional runtime dependency
    torch = None


class BoneModelService:
    def __init__(self, model_path: Path | None, labels: list[str]) -> None:
        self.labels = self._load_labels(model_path, labels)
        self.model_path = model_path
        self.model = None
        self.device = "cpu"
        self.load_error: str | None = None

        if model_path:
            self._load_model(model_path)

    @property
    def is_ready(self) -> bool:
        return self.model is not None

    def predict(self, image: np.ndarray) -> PredictionResult:
        if not self.is_ready:
            reason = "No trained model is configured."
            if self.load_error:
                reason = f"Model could not be loaded: {self.load_error}"
            return PredictionResult(
                status="analysis_only",
                note=f"{reason} Returning preprocessing and feature analysis only.",
            )

        assert torch is not None
        tensor = torch.from_numpy(image.astype("float32") / 255.0)
        tensor = tensor.unsqueeze(0).unsqueeze(0).to(self.device)

        with torch.no_grad():
            logits = self.model(tensor)
            if isinstance(logits, (tuple, list)):
                logits = logits[0]
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

        top_index = int(np.argmax(probs))
        top_label = self.labels[top_index] if top_index < len(self.labels) else str(top_index)

        return PredictionResult(
            status="model_prediction",
            labels=self.labels[: len(probs)],
            probabilities=[round(float(p), 6) for p in probs],
            top_label=top_label,
            confidence=round(float(probs[top_index]), 6),
            note="Prediction generated by the configured trained model.",
        )

    def _load_model(self, model_path: Path) -> None:
        if torch is None:
            self.load_error = "PyTorch is not installed"
            return
        if not model_path.exists():
            self.load_error = f"File not found: {model_path}"
            return

        try:
            self.model = torch.jit.load(str(model_path), map_location=self.device)
            self.model.eval()
        except Exception as exc:
            self.load_error = str(exc)
            self.model = None

    def _load_labels(self, model_path: Path | None, fallback: list[str]) -> list[str]:
        if not model_path:
            return fallback

        candidates = [
            model_path.with_suffix(".labels.json"),
            model_path.parent / "bone_model.labels.json",
            model_path.parent / "labels.json",
        ]
        for path in candidates:
            if not path.exists():
                continue
            try:
                labels = json.loads(path.read_text(encoding="utf-8"))
                if isinstance(labels, list) and all(isinstance(label, str) for label in labels):
                    return labels
            except Exception:
                continue
        return fallback
