from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .feature_model import extract_feature_model_vector
from .processor import MedicalImageProcessor
from .schemas import PredictionResult

try:
    import torch
except Exception:  # pragma: no cover - optional runtime dependency
    torch = None


class BoneModelService:
    def __init__(self, model_path: Path | None, labels: list[str]) -> None:
        self.labels = self._load_labels(model_path, labels)
        self.model_path = model_path
        self.model = None
        self.model_kind: str | None = None
        self.device = "cpu"
        self.load_error: str | None = None
        self.model_note = ""
        self.test_accuracy: float | None = None
        self.train_distance_p95: float | None = None
        self.feature_processor = MedicalImageProcessor()

        if model_path:
            self._load_model(model_path)

    @property
    def is_ready(self) -> bool:
        return self.model is not None

    def predict(self, image: np.ndarray) -> PredictionResult:
        if not self.is_ready:
            reason = "No trained model is configured."
            if self.load_error:
                reason = f"Model could not be loaded: {self.load_error}"
            return PredictionResult(
                status="analysis_only",
                note=f"{reason} Returning preprocessing and feature analysis only.",
            )

        if self.model_kind in {"feature_centroid", "feature_knn"}:
            return self._predict_feature_model(image)

        assert torch is not None
        tensor = torch.from_numpy(image.astype("float32") / 255.0)
        tensor = tensor.unsqueeze(0).unsqueeze(0).to(self.device)

        with torch.no_grad():
            logits = self.model(tensor)
            if isinstance(logits, (tuple, list)):
                logits = logits[0]
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

        top_index = int(np.argmax(probs))
        top_label = self.labels[top_index] if top_index < len(self.labels) else str(top_index)

        return PredictionResult(
            status="model_prediction",
            labels=self.labels[: len(probs)],
            probabilities=[round(float(p), 6) for p in probs],
            top_label=top_label,
            confidence=round(float(probs[top_index]), 6),
            note="Prediction generated by the configured trained model.",
        )

    def _load_model(self, model_path: Path) -> None:
        if not model_path.exists():
            self.load_error = f"File not found: {model_path}"
            return

        if model_path.suffix.lower() == ".json":
            self._load_feature_centroid_model(model_path)
            return

        if torch is None:
            self.load_error = "PyTorch is not installed"
            return

        try:
            self.model = torch.jit.load(str(model_path), map_location=self.device)
            self.model.eval()
            self.model_kind = "torchscript"
        except Exception as exc:
            self.load_error = str(exc)
            self.model = None
            self.model_kind = None

    def _load_feature_centroid_model(self, model_path: Path) -> None:
        try:
            payload = json.loads(model_path.read_text(encoding="utf-8"))
            if payload.get("model_type") not in {"feature_centroid", "feature_knn"}:
                raise ValueError("Unsupported JSON model_type")
            labels = payload.get("labels")
            feature_mean = payload.get("feature_mean")
            feature_scale = payload.get("feature_scale")
            if not labels or not feature_mean or not feature_scale:
                raise ValueError("Feature model JSON is missing required fields")

            self.labels = [str(label) for label in labels]
            self.model = {
                "feature_mean": np.asarray(feature_mean, dtype=np.float32),
                "feature_scale": np.asarray(feature_scale, dtype=np.float32),
                "k": int(payload.get("k", 5)),
            }
            self.model_note = str(payload.get("note") or "")
            self.test_accuracy = self._read_test_accuracy(payload)
            if payload.get("model_type") == "feature_knn":
                train_vectors = np.asarray(payload.get("train_vectors"), dtype=np.float32)
                self.model["train_vectors"] = train_vectors
                self.model["train_targets"] = np.asarray(payload.get("train_targets"), dtype=np.int64)
                self.train_distance_p95 = self._estimate_train_distance_p95(train_vectors)
            else:
                self.model["centroids"] = np.asarray(payload.get("centroids"), dtype=np.float32)
            self.model_kind = payload.get("model_type")
        except Exception as exc:
            self.load_error = str(exc)
            self.model = None
            self.model_kind = None

    def _predict_feature_model(self, image: np.ndarray) -> PredictionResult:
        assert isinstance(self.model, dict)
        features = extract_feature_model_vector(image, self.feature_processor)
        mean = self.model["feature_mean"]
        scale = self.model["feature_scale"]
        normalized = (features - mean) / np.maximum(scale, 1e-6)

        if self.model_kind == "feature_knn":
            train_vectors = self.model["train_vectors"]
            train_targets = self.model["train_targets"]
            distances = np.linalg.norm(train_vectors - normalized, axis=1)
            k = max(1, min(int(self.model["k"]), len(distances)))
            neighbor_indices = np.argsort(distances)[:k]
            weights = 1.0 / np.maximum(distances[neighbor_indices], 1e-6)
            probs = np.zeros(len(self.labels), dtype=np.float32)
            for index, weight in zip(neighbor_indices, weights):
                target = int(train_targets[index])
                if 0 <= target < len(probs):
                    probs[target] += float(weight)
            probs = probs / np.maximum(probs.sum(), 1e-12)
        else:
            centroids = self.model["centroids"]
            distances = np.linalg.norm(centroids - normalized, axis=1)
            scores = -distances
            scores = scores - scores.max()
            exp_scores = np.exp(scores)
            probs = exp_scores / np.maximum(exp_scores.sum(), 1e-12)

        top_index = int(np.argmax(probs))
        raw_confidence = float(probs[top_index])
        sorted_probs = np.sort(probs)
        second_prob = float(sorted_probs[-2]) if len(sorted_probs) > 1 else 0.0
        margin = max(0.0, raw_confidence - second_prob)
        min_distance = float(np.min(distances)) if "distances" in locals() and len(distances) else None
        proximity = self._distance_proximity(min_distance)
        top_label = self.labels[top_index] if top_index < len(self.labels) else str(top_index)
        calibrated_confidence = self._calibrate_feature_confidence(
            top_label=top_label,
            raw_confidence=raw_confidence,
            margin=margin,
            proximity=proximity,
        )

        if not self._feature_model_is_clinically_usable(top_label, raw_confidence, calibrated_confidence, min_distance):
            reason_parts = [
                "Lightweight feature model is not reliable enough for a pathology conclusion.",
                f"Top candidate: {top_label} (raw={raw_confidence:.2f}, calibrated={calibrated_confidence:.2f}).",
            ]
            if self.test_accuracy is not None:
                reason_parts.append(f"Validation accuracy={self.test_accuracy:.2f}.")
            if self.model_note:
                reason_parts.append(self.model_note)
            return PredictionResult(
                status="analysis_only",
                labels=self.labels[: len(probs)],
                probabilities=[round(float(p), 6) for p in probs],
                note=" ".join(reason_parts),
            )

        return PredictionResult(
            status="model_prediction",
            labels=self.labels[: len(probs)],
            probabilities=[round(float(p), 6) for p in probs],
            top_label=top_label,
            confidence=round(float(calibrated_confidence), 6),
            note=(
                f"Screening suggestion from the trained {self.model_kind} bone model. "
                "Confidence is calibrated from vote margin and feature distance. "
                "This is not a standalone diagnosis; compare with the original film and clinical findings."
            ),
        )

    def _read_test_accuracy(self, payload: dict) -> float | None:
        try:
            value = payload.get("metrics", {}).get("test", {}).get("accuracy")
            return float(value) if value is not None else None
        except Exception:
            return None

    def _estimate_train_distance_p95(self, train_vectors: np.ndarray) -> float | None:
        if train_vectors.ndim != 2 or len(train_vectors) < 3:
            return None
        distances = []
        for index, vector in enumerate(train_vectors):
            row = np.linalg.norm(train_vectors - vector, axis=1)
            row[index] = np.inf
            nearest = float(np.min(row))
            if np.isfinite(nearest):
                distances.append(nearest)
        if not distances:
            return None
        return float(np.percentile(np.asarray(distances, dtype=np.float32), 95))

    def _distance_proximity(self, distance: float | None) -> float:
        if distance is None:
            return 0.5
        reference = self.train_distance_p95
        if reference is None or reference <= 1e-6:
            return 0.5
        return float(np.exp(-max(distance, 0.0) / reference))

    def _calibrate_feature_confidence(
        self,
        top_label: str,
        raw_confidence: float,
        margin: float,
        proximity: float,
    ) -> float:
        # Fixed display policy:
        # - raw_confidence is the KNN/centroid model vote.
        # - margin separates the top label from the runner-up.
        # - proximity rewards images close to the training feature space.
        # A unanimous fracture vote is intentionally shown as a strong screening
        # finding, while non-fracture/demo results stay conservative.
        base = 0.62 * raw_confidence + 0.28 * margin + 0.10 * proximity
        if top_label == "fracture" and raw_confidence >= 0.98 and margin >= 0.95:
            base = max(base, 0.95)
        elif raw_confidence >= 0.9 and margin >= 0.75:
            base = max(base, 0.88)
        return round(float(min(raw_confidence, base)), 6)

    def _feature_model_is_clinically_usable(
        self,
        top_label: str,
        raw_confidence: float,
        confidence: float,
        distance: float | None,
    ) -> bool:
        note = self.model_note.lower()
        near_training_distribution = not (
            distance is not None
            and self.train_distance_p95 is not None
            and distance > self.train_distance_p95 * 1.5
        )
        # The bundled feature model is only a demo, but a very strong fracture
        # candidate can still be shown as a screening suggestion for the thesis UI.
        if ("demo model" in note or "demo" in note or "synthetic" in note) and top_label == "fracture":
            return raw_confidence >= 0.98 and confidence >= 0.8
        if "demo model" in note or "demo" in note or "synthetic" in note:
            return False
        if self.test_accuracy is not None and self.test_accuracy < 0.75:
            return top_label == "fracture" and raw_confidence >= 0.98 and confidence >= 0.8
        if confidence < 0.6:
            return False
        if not near_training_distribution:
            return False
        return True

    def _load_labels(self, model_path: Path | None, fallback: list[str]) -> list[str]:
        if not model_path:
            return fallback

        candidates = [
            model_path.with_suffix(".labels.json"),
            model_path.parent / "bone_model.labels.json",
            model_path.parent / "labels.json",
        ]
        for path in candidates:
            if not path.exists():
                continue
            try:
                labels = json.loads(path.read_text(encoding="utf-8"))
                if isinstance(labels, list) and all(isinstance(label, str) for label in labels):
                    return labels
            except Exception:
                continue
        return fallback
